jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Run antora
      uses: docker://antora/antora:2.3.1
      with:
        args: site-gh-pages.yml
    - continue-on-error: true
      name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        COMMIT_MESSAGE: '[docs] Publishing the docs for commit(s) ${{github.sha}}'
        FOLDER: gh-pages
        GITHUB_TOKEN: ${{github.token}}
name: docs
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
